### ISSUE TITLE
Superhintergrund stürzt ab

### ISSUE THREAD

**Issue by darosto** [berlinux2016/MIUI11#20]
- **MIUI Version:** 12
- **Device name:** Mi10

**Screenshot/Description:**
Superhintergrund stürzt ab. beim wechseln auf Englisch funktionierts bestens. Nehme mal an es hat mit der Deutschen Übersetzung was zu tun.
error log:
android.content.res.Resources$NotFoundException: Resource ID #0x0
	at android.content.res.ResourcesImpl.getValueForDensity(Unknown Source:32)
	at android.content.res.Resources.getDrawableForDensity(Unknown Source:8)
	at android.content.res.Resources.getDrawable(Unknown Source:1)
	at android.content.res.Resources.getDrawable(Unknown Source:1)
	at com.miui.miwallpaper.widget.SuperWallpaperItem.setBaseContents(Unknown Source:57)
	at com.miui.miwallpaper.activity.SuperWallpaperListActivity$1.onPostExecute(Unknown Source:208)
	at com.miui.miwallpaper.activity.SuperWallpaperListActivity$1.onPostExecute(Unknown Source:2)
	at android.os.AsyncTask.finish(Unknown Source:10)
	at android.os.AsyncTask.access$900(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(Unknown Source:28)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loop(Unknown Source:249)
	at android.app.ActivityThread.main(Unknown Source:98)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:282)

**Comment by Henry2o1o** [comment]
aktuelle Version vom 18.

**Comment by darosto** [comment]
yes

**Comment by darosto** [comment]
![IMG_20200620_134305](https://user-images.githubusercontent.com/3748261/85200996-288c2f80-b2fc-11ea-95fe-f081e02631b7.jpg)

**Comment by Henry2o1o** [comment]
scheint so, als ob das nur in der Stable so ist?

**Comment by MeiGuddet** [comment]
Sollte inzwischen behoben sein.
